/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomColumn {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'dataType' : DataType,
}
export type CustomFieldValue = { 'nat' : bigint } |
  { 'float' : number } |
  { 'string' : string } |
  { 'tradeDirection' : TradeDirection } |
  { 'tradeType' : TradeType };
export interface CustomFieldView {
  'value' : CustomFieldValue,
  'columnId' : string,
}
export type DataType = { 'nat' : null } |
  { 'float' : null } |
  { 'string' : null } |
  { 'tradeDirection' : null } |
  { 'tradeType' : null };
export type TradeDirection = { 'buy' : null } |
  { 'sell' : null };
export type TradeType = { 'forex' : null } |
  { 'stock' : null } |
  { 'crypto' : null };
export interface TradeView {
  'id' : string,
  'direction' : TradeDirection,
  'tradeType' : TradeType,
  'userId' : Principal,
  'customFields' : Array<CustomFieldView>,
  'price' : number,
  'amount' : bigint,
  'symbol' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomColumn' : ActorMethod<[string, string, DataType], undefined>,
  'createTrade' : ActorMethod<
    [string, string, bigint, number, TradeDirection, TradeType],
    undefined
  >,
  'deleteCustomColumn' : ActorMethod<[string], undefined>,
  'deleteTrade' : ActorMethod<[string], undefined>,
  'getAllTrades' : ActorMethod<[], Array<TradeView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomColumns' : ActorMethod<[], Array<[string, CustomColumn]>>,
  'getCustomFieldValue' : ActorMethod<[string, string], CustomFieldValue>,
  'getCustomFieldsByColumn' : ActorMethod<
    [string],
    Array<[string, CustomFieldValue]>
  >,
  'getCustomFieldsForTrade' : ActorMethod<[string], Array<CustomFieldView>>,
  'getTrade' : ActorMethod<[string], TradeView>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomFieldValue' : ActorMethod<
    [string, string, CustomFieldValue],
    undefined
  >,
  'updateTrade' : ActorMethod<
    [string, string, bigint, number, TradeDirection, TradeType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];