/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DataType = IDL.Variant({
  'nat' : IDL.Null,
  'float' : IDL.Null,
  'string' : IDL.Null,
  'tradeDirection' : IDL.Null,
  'tradeType' : IDL.Null,
});
export const TradeDirection = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const TradeType = IDL.Variant({
  'forex' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const CustomFieldValue = IDL.Variant({
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'string' : IDL.Text,
  'tradeDirection' : TradeDirection,
  'tradeType' : TradeType,
});
export const CustomFieldView = IDL.Record({
  'value' : CustomFieldValue,
  'columnId' : IDL.Text,
});
export const TradeView = IDL.Record({
  'id' : IDL.Text,
  'direction' : TradeDirection,
  'tradeType' : TradeType,
  'userId' : IDL.Principal,
  'customFields' : IDL.Vec(CustomFieldView),
  'price' : IDL.Float64,
  'amount' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomColumn = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'dataType' : DataType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomColumn' : IDL.Func([IDL.Text, IDL.Text, DataType], [], []),
  'createTrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, TradeDirection, TradeType],
      [],
      [],
    ),
  'deleteCustomColumn' : IDL.Func([IDL.Text], [], []),
  'deleteTrade' : IDL.Func([IDL.Text], [], []),
  'getAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomColumns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CustomColumn))],
      ['query'],
    ),
  'getCustomFieldValue' : IDL.Func(
      [IDL.Text, IDL.Text],
      [CustomFieldValue],
      ['query'],
    ),
  'getCustomFieldsByColumn' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, CustomFieldValue))],
      ['query'],
    ),
  'getCustomFieldsForTrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomFieldView)],
      ['query'],
    ),
  'getTrade' : IDL.Func([IDL.Text], [TradeView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomFieldValue' : IDL.Func(
      [IDL.Text, IDL.Text, CustomFieldValue],
      [],
      [],
    ),
  'updateTrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, TradeDirection, TradeType],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DataType = IDL.Variant({
    'nat' : IDL.Null,
    'float' : IDL.Null,
    'string' : IDL.Null,
    'tradeDirection' : IDL.Null,
    'tradeType' : IDL.Null,
  });
  const TradeDirection = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const TradeType = IDL.Variant({
    'forex' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const CustomFieldValue = IDL.Variant({
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'string' : IDL.Text,
    'tradeDirection' : TradeDirection,
    'tradeType' : TradeType,
  });
  const CustomFieldView = IDL.Record({
    'value' : CustomFieldValue,
    'columnId' : IDL.Text,
  });
  const TradeView = IDL.Record({
    'id' : IDL.Text,
    'direction' : TradeDirection,
    'tradeType' : TradeType,
    'userId' : IDL.Principal,
    'customFields' : IDL.Vec(CustomFieldView),
    'price' : IDL.Float64,
    'amount' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomColumn = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'dataType' : DataType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomColumn' : IDL.Func([IDL.Text, IDL.Text, DataType], [], []),
    'createTrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, TradeDirection, TradeType],
        [],
        [],
      ),
    'deleteCustomColumn' : IDL.Func([IDL.Text], [], []),
    'deleteTrade' : IDL.Func([IDL.Text], [], []),
    'getAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomColumns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CustomColumn))],
        ['query'],
      ),
    'getCustomFieldValue' : IDL.Func(
        [IDL.Text, IDL.Text],
        [CustomFieldValue],
        ['query'],
      ),
    'getCustomFieldsByColumn' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, CustomFieldValue))],
        ['query'],
      ),
    'getCustomFieldsForTrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomFieldView)],
        ['query'],
      ),
    'getTrade' : IDL.Func([IDL.Text], [TradeView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomFieldValue' : IDL.Func(
        [IDL.Text, IDL.Text, CustomFieldValue],
        [],
        [],
      ),
    'updateTrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, TradeDirection, TradeType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };