/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomFieldView {
    value: CustomFieldValue;
    columnId: string;
}
export type CustomFieldValue = {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "string";
    string: string;
} | {
    __kind__: "tradeDirection";
    tradeDirection: TradeDirection;
} | {
    __kind__: "tradeType";
    tradeType: TradeType;
};
export interface CustomColumn {
    id: string;
    owner: Principal;
    name: string;
    dataType: DataType;
}
export interface UserProfile {
    name: string;
}
export interface TradeView {
    id: string;
    direction: TradeDirection;
    tradeType: TradeType;
    userId: Principal;
    customFields: Array<CustomFieldView>;
    price: number;
    amount: bigint;
    symbol: string;
}
export enum DataType {
    nat = "nat",
    float_ = "float",
    string_ = "string",
    tradeDirection = "tradeDirection",
    tradeType = "tradeType"
}
export enum TradeDirection {
    buy = "buy",
    sell = "sell"
}
export enum TradeType {
    forex = "forex",
    stock = "stock",
    crypto = "crypto"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomColumn(id: string, name: string, dataType: DataType): Promise<void>;
    createTrade(id: string, symbol: string, amount: bigint, price: number, direction: TradeDirection, tradeType: TradeType): Promise<void>;
    deleteCustomColumn(id: string): Promise<void>;
    deleteTrade(id: string): Promise<void>;
    getAllTrades(): Promise<Array<TradeView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomColumns(): Promise<Array<[string, CustomColumn]>>;
    getCustomFieldValue(tradeId: string, columnId: string): Promise<CustomFieldValue>;
    getCustomFieldsByColumn(columnId: string): Promise<Array<[string, CustomFieldValue]>>;
    getCustomFieldsForTrade(tradeId: string): Promise<Array<CustomFieldView>>;
    getTrade(id: string): Promise<TradeView>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCustomFieldValue(tradeId: string, columnId: string, value: CustomFieldValue): Promise<void>;
    updateTrade(id: string, symbol: string, amount: bigint, price: number, direction: TradeDirection, tradeType: TradeType): Promise<void>;
}
import type { CustomColumn as _CustomColumn, CustomFieldValue as _CustomFieldValue, CustomFieldView as _CustomFieldView, DataType as _DataType, TradeDirection as _TradeDirection, TradeType as _TradeType, TradeView as _TradeView, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomColumn(arg0: string, arg1: string, arg2: DataType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomColumn(arg0, arg1, to_candid_DataType_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomColumn(arg0, arg1, to_candid_DataType_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createTrade(arg0: string, arg1: string, arg2: bigint, arg3: number, arg4: TradeDirection, arg5: TradeType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n5(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n5(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteCustomColumn(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomColumn(arg0);
            return result;
        }
    }
    async deleteTrade(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getAllTrades(): Promise<Array<TradeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomColumns(): Promise<Array<[string, CustomColumn]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomColumns();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomColumns();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomFieldValue(arg0: string, arg1: string): Promise<CustomFieldValue> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomFieldValue(arg0, arg1);
                return from_candid_CustomFieldValue_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomFieldValue(arg0, arg1);
            return from_candid_CustomFieldValue_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomFieldsByColumn(arg0: string): Promise<Array<[string, CustomFieldValue]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomFieldsByColumn(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomFieldsByColumn(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomFieldsForTrade(arg0: string): Promise<Array<CustomFieldView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomFieldsForTrade(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomFieldsForTrade(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: string): Promise<TradeView> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_TradeView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_TradeView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCustomFieldValue(arg0: string, arg1: string, arg2: CustomFieldValue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCustomFieldValue(arg0, arg1, to_candid_CustomFieldValue_n32(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCustomFieldValue(arg0, arg1, to_candid_CustomFieldValue_n32(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTrade(arg0: string, arg1: string, arg2: bigint, arg3: number, arg4: TradeDirection, arg5: TradeType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n5(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n5(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_CustomColumn_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomColumn): CustomColumn {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CustomFieldValue_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomFieldValue): CustomFieldValue {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CustomFieldView_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomFieldView): CustomFieldView {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DataType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataType): DataType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TradeView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeView): TradeView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    direction: _TradeDirection;
    tradeType: _TradeType;
    userId: Principal;
    customFields: Array<_CustomFieldView>;
    price: number;
    amount: bigint;
    symbol: string;
}): {
    id: string;
    direction: TradeDirection;
    tradeType: TradeType;
    userId: Principal;
    customFields: Array<CustomFieldView>;
    price: number;
    amount: bigint;
    symbol: string;
} {
    return {
        id: value.id,
        direction: from_candid_TradeDirection_n12(_uploadFile, _downloadFile, value.direction),
        tradeType: from_candid_TradeType_n14(_uploadFile, _downloadFile, value.tradeType),
        userId: value.userId,
        customFields: from_candid_vec_n16(_uploadFile, _downloadFile, value.customFields),
        price: value.price,
        amount: value.amount,
        symbol: value.symbol
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _CustomFieldValue;
    columnId: string;
}): {
    value: CustomFieldValue;
    columnId: string;
} {
    return {
        value: from_candid_CustomFieldValue_n19(_uploadFile, _downloadFile, value.value),
        columnId: value.columnId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    dataType: _DataType;
}): {
    id: string;
    owner: Principal;
    name: string;
    dataType: DataType;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        dataType: from_candid_DataType_n28(_uploadFile, _downloadFile, value.dataType)
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _CustomColumn]): [string, CustomColumn] {
    return [
        value[0],
        from_candid_CustomColumn_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _CustomFieldValue]): [string, CustomFieldValue] {
    return [
        value[0],
        from_candid_CustomFieldValue_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeDirection {
    return "buy" in value ? TradeDirection.buy : "sell" in value ? TradeDirection.sell : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
}): TradeType {
    return "forex" in value ? TradeType.forex : "stock" in value ? TradeType.stock : "crypto" in value ? TradeType.crypto : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nat: bigint;
} | {
    float: number;
} | {
    string: string;
} | {
    tradeDirection: _TradeDirection;
} | {
    tradeType: _TradeType;
}): {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "string";
    string: string;
} | {
    __kind__: "tradeDirection";
    tradeDirection: TradeDirection;
} | {
    __kind__: "tradeType";
    tradeType: TradeType;
} {
    return "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "string" in value ? {
        __kind__: "string",
        string: value.string
    } : "tradeDirection" in value ? {
        __kind__: "tradeDirection",
        tradeDirection: from_candid_TradeDirection_n12(_uploadFile, _downloadFile, value.tradeDirection)
    } : "tradeType" in value ? {
        __kind__: "tradeType",
        tradeType: from_candid_TradeType_n14(_uploadFile, _downloadFile, value.tradeType)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nat: null;
} | {
    float: null;
} | {
    string: null;
} | {
    tradeDirection: null;
} | {
    tradeType: null;
}): DataType {
    return "nat" in value ? DataType.nat : "float" in value ? DataType.float : "string" in value ? DataType.string : "tradeDirection" in value ? DataType.tradeDirection : "tradeType" in value ? DataType.tradeType : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomFieldView>): Array<CustomFieldView> {
    return value.map((x)=>from_candid_CustomFieldView_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _CustomColumn]>): Array<[string, CustomColumn]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _CustomFieldValue]>): Array<[string, CustomFieldValue]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeView>): Array<TradeView> {
    return value.map((x)=>from_candid_TradeView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CustomFieldValue_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomFieldValue): _CustomFieldValue {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_DataType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataType): _DataType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TradeDirection_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "string";
    string: string;
} | {
    __kind__: "tradeDirection";
    tradeDirection: TradeDirection;
} | {
    __kind__: "tradeType";
    tradeType: TradeType;
}): {
    nat: bigint;
} | {
    float: number;
} | {
    string: string;
} | {
    tradeDirection: _TradeDirection;
} | {
    tradeType: _TradeType;
} {
    return value.__kind__ === "nat" ? {
        nat: value.nat
    } : value.__kind__ === "float" ? {
        float: value.float
    } : value.__kind__ === "string" ? {
        string: value.string
    } : value.__kind__ === "tradeDirection" ? {
        tradeDirection: to_candid_TradeDirection_n5(_uploadFile, _downloadFile, value.tradeDirection)
    } : value.__kind__ === "tradeType" ? {
        tradeType: to_candid_TradeType_n7(_uploadFile, _downloadFile, value.tradeType)
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataType): {
    nat: null;
} | {
    float: null;
} | {
    string: null;
} | {
    tradeDirection: null;
} | {
    tradeType: null;
} {
    return value == DataType.nat ? {
        nat: null
    } : value == DataType.float ? {
        float_: null
    } : value == DataType.string ? {
        string_: null
    } : value == DataType.tradeDirection ? {
        tradeDirection: null
    } : value == DataType.tradeType ? {
        tradeType: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeDirection.buy ? {
        buy: null
    } : value == TradeDirection.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
} {
    return value == TradeType.forex ? {
        forex: null
    } : value == TradeType.stock ? {
        stock: null
    } : value == TradeType.crypto ? {
        crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
